---
# tasks file for cleanup
- name: stoping jenkins's service
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop:
    - jenkins
    - nginx

- name: delete packages
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
    autoclean: yes
    autoremove: yes
  loop: "{{ packages }}"
 
- name: Uninstall programs
  command: apt-get remove -y "{{ item }}"
  loop: "{{ packages }}"

- name: remove Jenkins repository
  apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: absent
